### ISSUE TITLE
How to dowload files from piping-ui-web via cmdline (curl)

### ISSUE THREAD

**Issue by oldunclez** [nwtgck/piping-ui-web#1510]
Hi

Is it possbile to download files from piping-ui-web via cmdline (curl) ?
I try  curl  https://piping-ui.org/xxxx  
It only download the html code , not the files .
Thank you .

**Comment by nwtgck** [comment]
Hello,

You can see the server URL in the red in the following image.
<img width="675" alt="Screenshot 2023-04-11 at 8 23 02" src="https://user-images.githubusercontent.com/10933561/231017644-d3a4dd4f-e2c9-4bf5-bb4a-a1ae5236fa80.png">

The server transfers your data. In this case you can do `curl https://ppng.io/hoge`. Make sure passwordless is off.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/10933561/231017830-69fec7df-48e3-4f2b-bad3-87abbddd9b8b.png">

You can use a password for encryption which is gpg-compatible.
<img width="637" alt="image" src="https://user-images.githubusercontent.com/10933561/231017882-8a251442-d5e1-4227-9d6b-8cdd26eeff12.png">
